# lnmp

mysql:
  image: mysql:5.7
  container_name: mysql
  hostname: mysql
  ports:
  - "3306:3306"
  volumes:
  - ./mysql/data:/var/lib/mysql
  - ./mysql/conf:/etc/mysql/conf.d
  - ./mysql/logs:/logs
  environment:
  - MYSQL_ROOT_PASSWORD=root

redis:
  image: redis:4
  container_name: redis
  hostname: redis
  ports:
  - "6379:6379"

php:
  build: ./phpfpm
  container_name: php
  hostname: php
  ports:
    - "9000:9000"
  links:
    - mysql:mysql
    - redis:redis
  volumes:
    - /Users/chenyinshan/code:/www

nginx:
  image: nginx:latest
  container_name: nginx
  hostname: nginx
  ports:
  - "80:80"
  volumes:
  - /Users/chenyinshan/code:/www
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
  - php:PHP-FPM


  
